default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: spacex
  port: 5432
  pool: 100

test:
  adapter: postgresql
  port: 5432
  encoding: unicode
  database: spacex
  pool: 100
