default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: spacex_development
  port: 5432
  pool: 10

production:
  adapter: postgresql
  encoding: unicode
  database: spacex_production
  port: 5432
  pool: 10

test:
  adapter: postgresql
  port: 5432
  encoding: unicode
  database: spacex_test
  pool: 10
